#!/usr/bin/env python3
"""PreToolUse hook: block direct edits to ~/.claude/settings.json.

settings.json is generated by setup.py. Direct edits will be overwritten.
"""

import json
import os
import sys

SETTINGS_PATH = os.path.join(os.path.expanduser("~"), ".claude", "settings.json")


def main() -> None:
    data = json.load(sys.stdin)
    tool_input = data.get("tool_input", {})
    file_path = tool_input.get("file_path", "") or tool_input.get("path", "")

    if not file_path:
        return

    if os.path.realpath(file_path) == os.path.realpath(SETTINGS_PATH):
        json.dump(
            {
                "decision": "block",
                "reason": "settings.json は setup.py から生成されます。setup.py を編集してから `python3 ~/.claude/setup.py` を実行してください。",
            },
            sys.stdout,
        )


if __name__ == "__main__":
    main()
